services:
  - type: web
    name: verixa-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        value: verixa_super_secret_jwt_key_that_is_at_least_32_bytes_long_1234567890!
      - key: JWT_EXPIRATION_MS
        value: 86400000
